---
title: "Application DSA3101"
format: html
---

```{r}
library(grouper)
library(ompr)
library(ompr.roi)
library(ROI.plugin.gurobi)
```

* Set `mytesting` to be your working directory

## Semester 2120

This one is a bit tricky because there were originally 5 topics, but the optimisation
could not find a solution because there were not enough students to form groups for 
5 topics!

```{r}
# Run the model on the dataset, having removed one undersubscribed topic
group_comp_df1 <- readRDS("data005-composition.rds")
group_pref_mat1 <- readRDS("data005-preference.rds")[, -c(1,6)]
df_list <- extract_student_info(group_comp_df1, "preference",  
                                self_formed_groups = 2,  
                                pref_mat = group_pref_mat1)
yaml_list <- extract_params_yaml("mdl02_input05.yml", "preference")
mdl2_5 <- prepare_model(df_list, yaml_list, "preference")
result <- solve_model(mdl2_5, with_ROI(solver="gurobi"))
groupr_assigned_df1 <- assign_groups(result, assignment = "preference",  
                                     dframe=group_comp_df1, yaml_list, 
                                     group_names="group_id")

# Extract the preference that each group had for the grouper-assigned topic
n_groups <- NROW(group_pref_mat1)
preference_alloc_topic <- rep(0, n_groups)
for(jj in 1:n_groups){
  group_id <- groupr_assigned_df1$group[jj]
  allocated_topic <- ((groupr_assigned_df1$subtopic-1)*4 + (groupr_assigned_df1$topic2))[jj]
  preference_alloc_topic[jj] <- group_pref_mat1[group_id, allocated_topic]
}
groupr_assigned_df1$pref_for_allocated_topic <- preference_alloc_topic

# Extract the manually allocated topics.
allocated_df1 <- readRDS("data005-allocated.rds")

# Calculate mean preference over students
allocated_pref_mean_2120 <- sum(allocated_df1$pref_for_allocated_topic*allocated_df1$size)/sum(allocated_df1$size)
# 8.16
groupr_pref_mean_2120 <-  sum(groupr_assigned_df1$pref_for_allocated_topic*groupr_assigned_df1$size)/sum(groupr_assigned_df1$size)
# 9.47

#groupr_assigned_df1 %>% select(1,2,3) %>% 
#  filter(subtopic==1) %>% unique() %>% NROW
```


## Semester 2210

```{r}
group_comp_df1 <- readRDS("data006-composition.rds")
group_pref_mat1 <- readRDS("data006-preference.rds")
allocated_df1 <- readRDS("data006-allocated.rds")

df_list <- extract_student_info(group_comp_df1, "preference",  
                                self_formed_groups = 2,  
                                pref_mat = group_pref_mat1)
yaml_list <- extract_params_yaml("mdl02_input06.yml", "preference")
mdl2_6 <- prepare_model(df_list, yaml_list, "preference")
result <- solve_model(mdl2_6, with_ROI(solver="gurobi"))
groupr_assigned_df1 <- assign_groups(result, assignment = "preference",  
                                     dframe=group_comp_df1, yaml_list, 
                                     group_names="group_id")

n_groups <- NROW(group_pref_mat1)
preference_alloc_topic <- rep(0, n_groups)
for(jj in 1:n_groups){
  group_id <- groupr_assigned_df1$group[jj]
  allocated_topic <- ((groupr_assigned_df1$subtopic-1)*7 + (groupr_assigned_df1$topic2))[jj]
  preference_alloc_topic[jj] <- group_pref_mat1[group_id, allocated_topic]
}
groupr_assigned_df1$pref_for_allocated_topic <- preference_alloc_topic

allocated_pref_mean_2210 <- 
 sum(allocated_df1$pref_for_allocated_topic*allocated_df1$size)/sum(allocated_df1$size) 
# 13.06
groupr_pref_mean_2210 <-  sum(groupr_assigned_df1$pref_for_allocated_topic*groupr_assigned_df1$size)/sum(groupr_assigned_df1$size)
# 13.32
```

## Semester 2220

```{r}
group_comp_df1 <- readRDS("data007-composition.rds")
group_pref_mat1 <- readRDS("data007-preference.rds")
allocated_df1 <- readRDS("data007-allocated.rds")

df_list <- extract_student_info(group_comp_df1, "preference",  
                                self_formed_groups = 2,  
                                pref_mat = group_pref_mat1)
yaml_list <- extract_params_yaml("mdl02_input07.yml", "preference")
mdl2_7 <- prepare_model(df_list, yaml_list, "preference")
result <- solve_model(mdl2_7, with_ROI(solver="gurobi"))
groupr_assigned_df1 <- assign_groups(result, assignment = "preference",  
                                     dframe=group_comp_df1, yaml_list, 
                                     group_names="group_id")

n_groups <- NROW(group_pref_mat1)
preference_alloc_topic <- rep(0, n_groups)
for(jj in 1:n_groups){
  group_id <- groupr_assigned_df1$group[jj]
  allocated_topic <- ((groupr_assigned_df1$subtopic-1)*7 + (groupr_assigned_df1$topic2))[jj]
  preference_alloc_topic[jj] <- group_pref_mat1[group_id, allocated_topic]
}
groupr_assigned_df1$pref_for_allocated_topic <- preference_alloc_topic

allocated_pref_mean_2220 <- 
  sum(allocated_df1$pref_for_allocated_topic*allocated_df1$size)/sum(allocated_df1$size)  
# 12.70
groupr_pref_mean_2220 <-  sum(groupr_assigned_df1$pref_for_allocated_topic*groupr_assigned_df1$size)/sum(groupr_assigned_df1$size)
# 13.51
```

## Semester 2310

```{r}
group_comp_df1 <- readRDS("data008-composition.rds")
group_pref_mat1 <- readRDS("data008-preference.rds")
allocated_df1 <- readRDS("data008-allocated.rds")

df_list <- extract_student_info(group_comp_df1, "preference",  
                                self_formed_groups = 2,  
                                pref_mat = group_pref_mat1)
yaml_list <- extract_params_yaml("mdl02_input08.yml", "preference")
mdl2_8 <- prepare_model(df_list, yaml_list, "preference")
result <- solve_model(mdl2_8, with_ROI(solver="gurobi"))
groupr_assigned_df1 <- assign_groups(result, assignment = "preference",  
                                     dframe=group_comp_df1, yaml_list, 
                                     group_names="group_id")

n_groups <- NROW(group_pref_mat1)
preference_alloc_topic <- rep(0, n_groups)
for(jj in 1:n_groups){
  group_id <- groupr_assigned_df1$group[jj]
  allocated_topic <- ((groupr_assigned_df1$subtopic-1)*5 + (groupr_assigned_df1$topic2))[jj]
  preference_alloc_topic[jj] <- group_pref_mat1[group_id, allocated_topic]
}
groupr_assigned_df1$pref_for_allocated_topic <- preference_alloc_topic

allocated_pref_mean_2310 <-  sum(allocated_df1$pref_for_allocated_topic*allocated_df1$size)/sum(allocated_df1$size)   
# 9.48
groupr_pref_mean_2310 <-  sum(groupr_assigned_df1$pref_for_allocated_topic*groupr_assigned_df1$size)/sum(groupr_assigned_df1$size) 
# 9.66
```

```{r}
dsa_tbl <- tibble(
       iteration = c(1,2,3,4),
       manual_pref = c(allocated_pref_mean_2120,
                       allocated_pref_mean_2210,
                       allocated_pref_mean_2220,
                       allocated_pref_mean_2310),
       grouper_pref = c(groupr_pref_mean_2120,
                       groupr_pref_mean_2210,
                       groupr_pref_mean_2220,
                       groupr_pref_mean_2310),
       class_size = c(62, 108, 89, 151),
       n_topics = c(4, 7, 7, 5),
       n_project_teams = c(7, 13 , 11, 18) 
         )

dsa_tbl %>% pivot_longer(cols=c("manual_pref", "grouper_pref"),
                         names_to = "assignment_type",
                         values_to="mean_preference") %>%
  ggplot(aes(x=iteration)) +
  geom_line(aes(y=mean_preference, color=assignment_type)) +
  geom_point(aes(y=mean_preference, color=assignment_type)) +
  labs(title="Comparison between grouper assignment and manual assignment",
       subtitle="Preference-based assignment",
       x="Iteration (Semester number)",
       y="Mean preference", col="Assignment type")
```

