---
title: "HS2914 tutorial allocation"
format: html
---

```{r}
library(groupr)
library(ompr)
library(ompr.roi)
library(ROI.plugin.gurobi)
```


```{r}
df1 <- readRDS("data009-composition.rds")
df_list <- extract_student_info(df1, "diversity",
                                demographic_cols = 2, skills = NULL, 
                                self_formed_groups = 1)
yaml_list <- extract_params_yaml("mdl01_input009.yml",
                                 "diversity")
m1 <- prepare_model(df_list, yaml_list, "diversity", w1=1.0)
result <- solve_model(m1, with_ROI(solver="gurobi", verbose=TRUE))
assigned_groups <- assign_groups(result, "diversity", df1, yaml_list, "student_id")
```

```{r}
library(tidyverse)
assigned_groups %>% ggplot() +
  geom_bar(aes(x=coded_major, fill = coded_major)) + facet_wrap(~assigned_grouping)

assigned_groups %>% ggplot() +
  geom_bar(aes(x=coded_major, fill = coded_major)) + facet_wrap(~topic)
```

The comparison below shows that, compared to the manual routine, the `groupr`
routines are able to balance the numbers of dsds (data science and statistics
majors) with the non-dsds majors better.

```{r}
assigned_groups %>% 
  select(topic, group, coded_major, assigned_grouping) %>% 
  pivot_longer(cols=c("topic", "assigned_grouping"), names_to="assign_mtd",
               values_to="assign_value") %>% 
  ggplot() + 
  geom_bar(aes(x=coded_major, fill=coded_major), show.legend = FALSE) + 
  facet_wrap(~assign_mtd + assign_value, nrow=2)
```


